close all;
clear all;

sessions = ["Dylan_210414_WT2_NPresults_short", ...
    "Dylan_210421_fChR2_NPresults_short_stim", "Dylan_210423_fChR2_NPresults_short", ...
    "Dylan_210422_fChR2_NPresults_short", "Dylan_210425_fChR2_NPresults_short", ...
    "Dylan_210511_fChR5_NPresults_short", "Dylan_210512_fChR5_NPresults_short", ...
    "Dylan_210514_fChR2_NPresults_short", "Dylan_210515_fChR5_NPresults_short", ...
    "Dylan_210606_fChR4_NPresults_short", "Dylan_210608_fChR4_NPresults_short", ...
    "Dylan_210614_fChR4_NPresults_short", "Dylan_210619_cChR1_NPresults_short", ...
    "Dylan_210620_cChR1_NPresults_short", "Dylan_210622_cChR1_NPresults_short", ...
    "Dylan_210623_cChR1_NPresults_short", "Dylan_220515_DJC002_NPresults_short", ...
    "Dylan_220516_DJC000_NPresults_short", "Dylan_220517_DJC002_NPresults_short", ...
    "Dylan_220518_DJC000_NPresults_short", "Dylan_220519_DJC000_NPresults_short", ...
    "Dylan_220519_DJC002_NPresults_short", "Dylan_220520_DJC000_NPresults_short", ...
    "Dylan_220520_DJC002_NPresults_short"];

reach_num = [74, 65, 62, 63, 52, 66, 54, 60, 68, 52, 73, 59, 80, 68, 71, ...
    68, 60, 53, 58, 58, 36, 70, 57, 45];

model_info = ["Shoulder Elv Angle Value", "Shoulder Extension Angle Value",   ...
    "Elbow Flex Value", "Ulna Radius Rot Value", "Wrist Angle Value", "Shoulder Elv Angle Speed",  ...
    "Shoulder Extension Angle Speed", "Elbow Flex Speed", "Ulna Radius Rot Speed", "Wrist Angle Speed",  ...
    "Pectoralis Clavicle Head Activation", "Biceps Short Head Activation", "Biceps Long Head Activation",   ...
    "Deltoid A Activation", "Triceps Short Head Activation", "Triceps Long Head Activation",   ...
    "Brachialis inner Head Activation", "Brachialis Outer Head Activation", "Anconeus Activation",   ...
    "Deltoid M Activation", "Short Anconeus Activation", "Subscapularis SuperiorHead Activation",  ...
    "Infraspinatus Activation", "Pronator Teres Activation", "Flexor Carpi Radialis Activation",  ...
    "Brachioradialis  Activation", "Pectoralis Clavicle Head", "Biceps Short Head", "Biceps Long Head",  ...
    "Deltoid A", "Triceps Short Head", "Triceps Long Head", "Brachialis inner Head", "Brachialis Outer Head",  ...
    "Anconeus", "Deltoid M", "Short Anconeus", "Subscapularis SuperiorHead", "Infraspinatus",  ...
    "Pronator Teres", "Flexor Carpi Radialis", "Brachioradialis"];
Predictor_names = ["Pos X", "Pos Y", "Pos Z", "Vel", "Vel X", "Vel X Up",  ...
    "Vel X Down", "Vel Y", "Vel Y Up", "Vel Y Down", "Vel Z", "Vel Z Up", ...
    "Vel Z Down", "Acc", "Acc X", "Acc X Up", "Acc X Down", "Acc Y", ...
    "Acc Y Up", "Acc Y Down", "Acc Z", "Acc Z Up", "Acc Z Down" "X Vel", ...
    "Y Vel", "Z Vel", "Vel Norm", "X Acc", "Y Acc", "Z Acc", "Acc Norm", ...
    "X Disp", "Y Disp", "Z Disp", "Disp Norm", model_info];

mkdir("C:\Lab\Elbow Data\Best Lags")

for feat = 1:length(Predictor_names)
    mkdir("C:\Lab\Elbow Data\Best Lags\" + string(Predictor_names(feat)))
    for session_num = [1, 2, 3, 4, 12, 14, 18, 21]
        for iter = 1:10
            load("C:\Lab\neuropixel_data\PC_cell_info\session_" + string(session_num) + ".mat", "PC")
            load("C:\Lab\Elbow Data\shuffled\Session " + string(session_num) + "\shuffled_" + string(iter) + "_neural.mat", "shuff_all_cells")

            PC_same = [];
            PC_opp = [];
            same = [];
            opp = [];

            for cell = 1:size(shuff_all_cells, 2)
                load("C:\Lab\Elbow Data\corrs\Session " + string(session_num) + "\shuffled_" + string(iter) + "cell_" + string(cell) + "_rmse", "RMSE")
                load("C:\Lab\Elbow Data\corrs\Session " + string(session_num) + "\shuffled_" + string(iter) + "cell_" + string(cell) + "_corrs", "corrs")
                [minValue, relIndex] = min(RMSE(31:end, feat));
                minIndex = relIndex + 30;
                if (minValue) <= 0.2
                    if PC(cell) == 1
                        if corrs(minIndex, feat) < 0
                            PC_opp = [PC_opp minIndex];
                        else
                            PC_same = [PC_same minIndex];
                        end
                    else
                        if corrs(minIndex, feat) < 0
                            opp = [opp minIndex];
                        else
                            same = [same minIndex];
                        end
                    end
                end
            end
            save("C:\Lab\Elbow Data\Best Lags\" + string(Predictor_names(feat)) + "\shuff " + string(iter) + "Session " + string(session_num) + " PC same", "PC_same")
            save("C:\Lab\Elbow Data\Best Lags\" + string(Predictor_names(feat)) + "\shuff " + string(iter) + "Session " + string(session_num) + " PC opp", "PC_opp")

            save("C:\Lab\Elbow Data\Best Lags\" + string(Predictor_names(feat)) + "\shuff " + string(iter) + "Session " + string(session_num) + " Non PC opp", "opp")
            save("C:\Lab\Elbow Data\Best Lags\" + string(Predictor_names(feat)) + "\shuff " + string(iter) + "Session " + string(session_num) + " Non PC same", "same")
        end
    end
end